
export const timezoneCurrencies = {
   "Pacific/Midway": { currencyCode: "USD", currencySymbol: "$" },
   "Pacific/Pago_Pago": { currencyCode: "USD", currencySymbol: "$" },
   "Pacific/Honolulu": { currencyCode: "USD", currencySymbol: "$" },
   "America/Juneau": { currencyCode: "USD", currencySymbol: "$" },
   "America/Los_Angeles": { currencyCode: "USD", currencySymbol: "$" },
   "America/Tijuana": { currencyCode: "MXN", currencySymbol: "$" },
   "America/Denver": { currencyCode: "USD", currencySymbol: "$" },
   "America/Phoenix": { currencyCode: "USD", currencySymbol: "$" },
   "America/Chihuahua": { currencyCode: "MXN", currencySymbol: "$" },
   "America/Mazatlan": { currencyCode: "MXN", currencySymbol: "$" },
   "America/Chicago": { currencyCode: "USD", currencySymbol: "$" },
   "America/Regina": { currencyCode: "CAD", currencySymbol: "$" },
   "America/Mexico_City": { currencyCode: "MXN", currencySymbol: "$" },
   "America/Monterrey": { currencyCode: "MXN", currencySymbol: "$" },
   "America/Guatemala": { currencyCode: "GTQ", currencySymbol: "Q" },
   "America/New_York": { currencyCode: "USD", currencySymbol: "$" },
   "America/Indiana/Indianapolis": { currencyCode: "USD", currencySymbol: "$" },
   "America/Bogota": { currencyCode: "COP", currencySymbol: "$" },
   "America/Lima": { currencyCode: "PEN", currencySymbol: "S/." },
   "America/Halifax": { currencyCode: "CAD", currencySymbol: "$" },
   "America/Caracas": { currencyCode: "VES", currencySymbol: "Bs." },
   "America/La_Paz": { currencyCode: "BOB", currencySymbol: "Bs." },
   "America/Santiago": { currencyCode: "CLP", currencySymbol: "$" },
   "America/St_Johns": { currencyCode: "CAD", currencySymbol: "$" },
   "America/Sao_Paulo": { currencyCode: "BRL", currencySymbol: "R$" },
   "America/Argentina/Buenos_Aires": { currencyCode: "ART", currencySymbol: "$" },
   "America/Guyana": { currencyCode: "GYD", currencySymbol: "$" },
   "America/Godthab": { currencyCode: "DKK", currencySymbol: "kr" },
   "Atlantic/South_Georgia": { currencyCode: "GBP", currencySymbol: "£" },
   "Atlantic/Azores": { currencyCode: "EUR", currencySymbol: "€" },
   "Atlantic/Cape_Verde": { currencyCode: "CVE", currencySymbol: "$" },
   "Europe/Dublin": { currencyCode: "EUR", currencySymbol: "€" },
   "Europe/London": { currencyCode: "GBP", currencySymbol: "£" },
   "Europe/Lisbon": { currencyCode: "EUR", currencySymbol: "€" },
   "Africa/Casablanca": { currencyCode: "MAD", currencySymbol: "د.م." },
   "Africa/Nairobi": { currencyCode: "KES", currencySymbol: "KSh" },
   "Europe/Belgrade": { currencyCode: "RSD", currencySymbol: "din" },
   "Europe/Bratislava": { currencyCode: "EUR", currencySymbol: "€" },
   "Europe/Budapest": { currencyCode: "HUF", currencySymbol: "Ft" },
   "Europe/Ljubljana": { currencyCode: "EUR", currencySymbol: "€" },
   "Europe/Prague": { currencyCode: "CZK", currencySymbol: "Kč" },
   "Europe/Sarajevo": { currencyCode: "BAM", currencySymbol: "KM" },
   "Europe/Skopje": { currencyCode: "MKD", currencySymbol: "ден" },
   "Europe/Warsaw": { currencyCode: "PLN", currencySymbol: "zł" },
   "Europe/Zagreb": { currencyCode: "HRK", currencySymbol: "kn" },
   "Europe/Brussels": { currencyCode: "EUR", currencySymbol: "€" },
   "Europe/Copenhagen": { currencyCode: "DKK", currencySymbol: "kr" },
   "Europe/Madrid": { currencyCode: "EUR", currencySymbol: "€" },
   "Europe/Paris": { currencyCode: "EUR", currencySymbol: "€" },
   "Europe/Amsterdam": { currencyCode: "EUR", currencySymbol: "€" },
   "Europe/Berlin": { currencyCode: "EUR", currencySymbol: "€" },
   "Europe/Rome": { currencyCode: "EUR", currencySymbol: "€" },
   "Europe/Stockholm": { currencyCode: "SEK", currencySymbol: "kr" },
   "Europe/Vienna": { currencyCode: "EUR", currencySymbol: "€" },
   "Europe/Zurich": { currencyCode: "CHF", currencySymbol: "CHF" },
   "Europe/Moscow": { currencyCode: "RUB", currencySymbol: "₽" },
   "Europe/Istanbul": { currencyCode: "TRY", currencySymbol: "₺" },
   "Africa/Cairo": { currencyCode: "EGP", currencySymbol: "E£" },
   "Africa/Harare": { currencyCode: "ZWL", currencySymbol: "$" },
   "Asia/Kuwait": { currencyCode: "KWD", currencySymbol: "د.ك" },
   "Asia/Riyadh": { currencyCode: "SAR", currencySymbol: "ر.س" },
   "Asia/Baghdad": { currencyCode: "IQD", currencySymbol: "ع.د" },
   "Asia/Tehran": { currencyCode: "IRR", currencySymbol: "﷼" },
   "Asia/Muscat": { currencyCode: "OMR", currencySymbol: "ر.ع." },
   "Asia/Baku": { currencyCode: "AZN", currencySymbol: "₼" },
   "Asia/Kabul": { currencyCode: "AFN", currencySymbol: "؋" },
   "Asia/Yekaterinburg": { currencyCode: "RUB", currencySymbol: "₽" },
   "Asia/Karachi": { currencyCode: "PKR", currencySymbol: "₨" },
   "Asia/Kolkata": { currencyCode: "INR", currencySymbol: "₹" },
   "Asia/Calcutta": { currencyCode: "INR", currencySymbol: "₹" },
   "Asia/Kathmandu": { currencyCode: "NPR", currencySymbol: "₨" },
   "Asia/Dhaka": { currencyCode: "BDT", currencySymbol: "৳" },
   "Asia/Colombo": { currencyCode: "LKR", currencySymbol: "₨" },
   "Asia/Almaty": { currencyCode: "KZT", currencySymbol: "₸" },
   "Asia/Rangoon": { currencyCode: "MMK", currencySymbol: "K" },
   "Asia/Bangkok": { currencyCode: "THB", currencySymbol: "฿" },
   "Asia/Jakarta": { currencyCode: "IDR", currencySymbol: "Rp" },
   "Asia/Ho_Chi_Minh": { currencyCode: "VND", currencySymbol: "₫" },
   "Asia/Shanghai": { currencyCode: "CNY", currencySymbol: "¥" },
   "Asia/Krasnoyarsk": { currencyCode: "RUB", currencySymbol: "₽" },
   "Asia/Hong_Kong": { currencyCode: "HKD", currencySymbol: "HK$" },
   "Asia/Taipei": { currencyCode: "TWD", currencySymbol: "NT$" },
   "Asia/Seoul": { currencyCode: "KRW", currencySymbol: "₩" },
   "Asia/Tokyo": { currencyCode: "JPY", currencySymbol: "¥" },
   "Asia/Irkutsk": { currencyCode: "RUB", currencySymbol: "₽" },
   "Asia/Yakutsk": { currencyCode: "RUB", currencySymbol: "₽" },
   "Australia/Darwin": { currencyCode: "AUD", currencySymbol: "A$" },
   "Australia/Adelaide": { currencyCode: "AUD", currencySymbol: "A$" },
   "Australia/Sydney": { currencyCode: "AUD", currencySymbol: "A$" },
   "Australia/Brisbane": { currencyCode: "AUD", currencySymbol: "A$" },
   "Australia/Hobart": { currencyCode: "AUD", currencySymbol: "A$" },
   "Asia/Vladivostok": { currencyCode: "RUB", currencySymbol: "₽" },
   "Pacific/Guam": { currencyCode: "USD", currencySymbol: "$" },
   "Pacific/Port_Moresby": { currencyCode: "PGK", currencySymbol: "K" },
   "Asia/Magadan": { currencyCode: "RUB", currencySymbol: "₽" },
   "Pacific/Noumea": { currencyCode: "XPF", currencySymbol: "₣" },
   "Pacific/Fiji": { currencyCode: "FJD", currencySymbol: "$" },
   "Asia/Kamchatka": { currencyCode: "RUB", currencySymbol: "₽" },
   "Pacific/Majuro": { currencyCode: "USD", currencySymbol: "$" },
   "Pacific/Auckland": { currencyCode: "NZD", currencySymbol: "NZ$" },
   "Pacific/Tongatapu": { currencyCode: "TOP", currencySymbol: "T$" },
   "Pacific/Apia": { currencyCode: "WST", currencySymbol: "T" }
};


export const getCurrentRate = {
ARS	: 898.816222,
AUD	: 1.502265,
BHD	: 0.376000,
BWP	: 13.735682,
BRL	: 5.254621,
GBP	: 0.782589,
BND	: 1.346645,
BGN	: 1.797268,
CAD	: 1.369253,
CLP	: 909.718075,
CNY	: 7.245461,
COP	: 3936.792456,
CZK	: 22.588863,
DKK	: 6.854658,
AED	: 3.672500,
EUR	: 0.918929,
HKD	: 7.810913,
HUF	: 358.048008,
ISK	: 137.591962,
INR	: 83.502221,
IDR	: 16254.247041,
IRR	: 42105.337926,
ILS	: 3.727806,
JPY	: 156.057923,
KZT	: 447.480106,
KWD	: 0.306449,
LYD	: 4.832489,
MYR	: 4.694827,
MUR	: 45.870209,
MXN	: 17.527017,
NPR	: 133.634165,
NZD	: 1.615082,
NOK	: 10.569694,
OMR	: 0.384994,
PKR	: 278.460325,
PHP	: 58.657954,
PLN	: 3.935279,
QAR	: 3.640000,
RON	: 4.573103,
RUB	: 88.996596,
SAR	: 3.750000,
SGD	: 1.346645,
ZAR	: 18.918002,
KRW	: 1366.500324,
LKR	: 302.847641,
SEK	: 10.416409,
CHF	: 0.891809,
TWD	: 32.316260,
THB	: 36.448295,
TTD	: 6.754124,
TRY	: 32.244778,
VES	: 3647467.529915,
};

