version: '3.8'
services:
  client-dev:
    build:
      context : .
      dockerfile : Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env 
      - .env.local 
  client-prod:
    build:
      context : .
      dockerfile : Dockerfile.prod
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env 
      - .env.local  
