-- AlterTable
ALTER TABLE "subscriptionDetail" ALTER COLUMN "endAt" SET DATA TYPE BIGINT,
ALTER COLUMN "currentEnd" SET DATA TYPE BIGINT,
ALTER COLUMN "currentStart" SET DATA TYPE BIGINT,
ALTER COLUMN "expiresBy" SET DATA TYPE BIGINT;
