name: Azure CI/CD Pipeline

on:
  push:
    branches: [ "azureProd" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [21.6.1]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create .env file
      run: echo "${{secrets.ENV_VARIABLE}}" > .env
    - name: Load .env varables
      run: |
        export $(grep -v '^#' .env | xargs)
    - run: pnpm install --frozen-lockfile
    - run: pnpm run build 
